// Code generated by mockery v2.16.0. DO NOT EDIT.

package test

import (
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// IPostgres is an autogenerated mock type for the IPostgres type
type IPostgres struct {
	mock.Mock
}

// Client provides a mock function with given fields:
func (_m *IPostgres) Client() *gorm.DB {
	ret := _m.Called()

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

type mockConstructorTestingTNewIPostgres interface {
	mock.TestingT
	Cleanup(func())
}

// NewIPostgres creates a new instance of IPostgres. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIPostgres(t mockConstructorTestingTNewIPostgres) *IPostgres {
	mock := &IPostgres{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
