version: '3.8'
services:
  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
#    restart: always
    env_file: .env
      # save 1 or more writes every 20 seconds to disk in case the server restarts
      # the implicit username is "default".
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - dbs:/redis/data
  postgres:
    container_name: postgres
    image: postgres:14
    ports:
      - "5432:5432"
#    restart: always
    env_file: .env
    volumes:
      - dbs:/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
volumes:
  dbs:
    driver: local