version: '3.8'
services:
  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    #    restart: always
      # save 1 or more writes every 20 seconds to disk in case the server restarts
      # the implicit username is "default".
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - dbs:/redis/data
  postgres:
    container_name: postgres
    image: postgres:14
    ports:
      - "${PG_PORT}:${PG_PORT}"
    #    restart: always
    volumes:
      - dbs:/postgresql/data
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
volumes:
  dbs:
    driver: local