// Code generated by mockery v2.20.0. DO NOT EDIT.

package test

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ITransaction is an autogenerated mock type for the ITransaction type
type ITransaction struct {
	mock.Mock
}

// Exec provides a mock function with given fields: ctx, fn
func (_m *ITransaction) Exec(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewITransaction interface {
	mock.TestingT
	Cleanup(func())
}

// NewITransaction creates a new instance of ITransaction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewITransaction(t mockConstructorTestingTNewITransaction) *ITransaction {
	mock := &ITransaction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
