// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"yehuizhang.com/go-webapp-gin/pkg/database"
	"yehuizhang.com/go-webapp-gin/pkg/flag_parser"
	"yehuizhang.com/go-webapp-gin/pkg/logger"
	"yehuizhang.com/go-webapp-gin/src/config"
	"yehuizhang.com/go-webapp-gin/src/controllers"
	"yehuizhang.com/go-webapp-gin/src/models/user"
	"yehuizhang.com/go-webapp-gin/src/server"
)

// Injectors from wire.go:

func BuildInjector() (Injector, func(), error) {
	healthController := &controllers.HealthController{}
	sugaredLogger := logger.InitLogger()
	flagParser := flag_parser.InitFlagParser()
	viper, err := config.InitConfig(flagParser, sugaredLogger)
	if err != nil {
		return Injector{}, nil, err
	}
	databaseDatabase := database.InitDatabase(viper, sugaredLogger)
	infoHandler := &user.InfoHandler{
		database: databaseDatabase,
		log:      sugaredLogger,
	}
	authHandler := &user.AuthHandler{
		database: databaseDatabase,
		log:      sugaredLogger,
	}
	userAuthController := &controllers.UserAuthController{
		logger:      sugaredLogger,
		infoHandler: infoHandler,
		authHandler: authHandler,
	}
	userInfoController := &controllers.UserInfoController{
		logger:      sugaredLogger,
		infoHandler: infoHandler,
	}
	router := &server.Router{
		healthController:   healthController,
		userAuthController: userAuthController,
		userInfoController: userInfoController,
		database:           databaseDatabase,
	}
	serverServer := &server.Server{
		router:   router,
		config:   viper,
		database: databaseDatabase,
		log:      sugaredLogger,
	}
	injector := Injector{
		server: serverServer,
		log:    sugaredLogger,
	}
	return injector, func() {
	}, nil
}
